name = "dgarbs51-blog"
compatibility_date = "2024-07-12"

[env.production]
name = "dgarbs51-blog"
routes = [
  { pattern = "dgarbs51.com", custom_domain = true },
  { pattern = "*.dgarbs51.com", custom_domain = true }
]

[build]
command = "npm run build"
cwd = "./"
